import { readFileSync, writeFileSync } from "node:fs";

const wasmPath = new URL("../target/wasm32-unknown-unknown/release/chopsticks.wasm", import.meta.url);
const outputPath = new URL("../frontend/bot_wasm.js", import.meta.url);
const bytes = readFileSync(wasmPath);
const base64 = bytes.toString("base64");

writeFileSync(
    outputPath,
    `// Generated by scripts/embed-wasm.mjs. Do not edit by hand.\nwindow.chopsticksBotWasmBase64 = "${base64}";\n`,
);

console.log(`Wrote ${outputPath.pathname}`);
